name: personal_data_platform
version: "1.0.0"
config-version: 2

profile: personal_data_platform
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  personal_data_platform:
    screen_time:
      +schema: base
      +materialized: view
      +tags: [screen_time_app_in_focus]
    marts:
      +schema: marts
      +materialized: view
      daily_screen_time:
        +tags: [screen_time_app_in_focus]
      daily_screen_time_total:
        +tags: [screen_time_app_in_focus]

data_tests:
  personal_data_platform:
    daily_screen_time_totals_match:
      +tags: [screen_time_app_in_focus]
    no_invalid_screen_time_duration:
      +tags: [screen_time_app_in_focus]
    daily_screen_time_keys_unique:
      +tags: [screen_time_app_in_focus]
    no_invalid_daily_screen_time_metrics:
      +tags: [screen_time_app_in_focus]
    daily_screen_time_total_matches_apps:
      +tags: [screen_time_app_in_focus]
